### ISSUE TITLE
Enable HTTPS

### ISSUE THREAD

**Issue by titanous** [jacobmerson/wedding-website#1]
Please enable HTTPS so that I can be sure that I'm getting your authentic wedding content without tampering, you just need to [check a box](https://help.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https). 🥂

**Comment by jacobmerson** [comment]
Good point...
There is some issue with the certificate which is preventing this for now...I contacted support, and will enable when possible.

**Comment by jacobmerson** [comment]
Done.
